### ISSUE TITLE
about 2D-loss-plot

### ISSUE THREAD

**Issue by harrylee999** [debcaldarola/fedsam#10]
hi! I have a little question
![image](https://github.com/debcaldarola/fedsam/assets/59381501/7575973a-19cb-4974-8586-ce3345366e3d)
it is easy to know \theta_1's coordinate is (0,0)

But how to compute the \theta_2's and \theta_3's coordinates in your paper?

**Comment by debcaldarola** [comment]
Hi!
I suggest you to take a look at this repo and the relative paper to better understand the visualization :) [https://github.com/tomgoldstein/loss-landscape](url)

Hope this helps!
