### ISSUE TITLE
How to compute the sharpness of minima

### ISSUE THREAD

**Issue by chenrxi** [debcaldarola/fedsam#3]
It is hard to find the code of computing dominant eigenvalue from [39], can you include the code of computing the sharpness of minima?
[39]On large- batch training for deep learning: Generalization gap and sharp minima

**Comment by debcaldarola** [comment]
Hi!
We used this repo as reference to compute the Hessian eigenvalues of the trained model https://github.com/noahgolmant/pytorch-hessian-eigenthings.

**Comment by chenrxi** [comment]
thank you and I will try it.

**Comment by chenrxi** [comment]
By the way, what does λ5 means and how to calculate it ?

**Comment by debcaldarola** [comment]
It's the 5th largest eigenvalue. When you compute the first N eigenvalues (N is an hyperparam you can set in the repo linked above) and you order decreasingly, lamba1 is the largest eigenvalue and lambda5 the fifth one
