### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Ulricalang** [debcaldarola/fedsam#6]
Hello, I'd like to ask, how to keep back propagation twice without reporting errors?

**Comment by debcaldarola** [comment]
Hi, which errors are you getting?

**Comment by Ulricalang** [comment]
Thank you very much for replying to my message. I have solved the problem. The error is pred = model(image). When I calculate the loss, using pred directly will report that the secondary back propagation cannot be carried out. Later, I expressed pred as model(x), and the error was solved.
